trigger:
  - main

variables:
  majorMinorVersion: 10.1
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]

  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
   nugetVersion: '$(majorMinorVersion).$(semanticVersion)'
  ${{ else }}:
   nugetVersion: '$(majorMinorVersion).$(semanticVersion)-prerelease'
  
name: '$(majorMinorVersion).$(semanticVersion)' #'$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)'

resources:
   repositories:
    - repository: yml
      type: git
      name: framework/yml templates
      ref: refs/heads/main
pool:
  vmImage: 'windows-latest'
stages:
  - template: /Nuget/azure-nuget-pipeline.yml@yml
    parameters:
      netVersion: '8.0.x'
      name: 'Fx.Common'
      solution: '**/*.sln'
      buildPlatform: 'AnyCPU'
      buildConfiguration: 'Release'
      nugetConfigLocation: 'nuget.config'
      
