name: Build Fx Comon Nuget

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
    packages: write
    
jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'BlueFox.Fx.Common.Nuget.sln'
      FEED_URL: 'https://nuget.pkg.github.com/bluefox/index.json'
      TOKEN: ${{secrets.GITHUB_TOKEN}} 

    runs-on: ubuntu-latest

    name: Build and publish nuget

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    
      - name: Pack solution
        run: |  
          cd .
          dotnet pack -c $BUILD_CONFIG -o out  

      # - name: Run tests
      #   run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
        
      - name: Push package
        # if: startsWith(github.ref, 'refs/heads/main')
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true -s $FEED_URL -k $TOKEN

